---

- name: Install Ruby RPM
  yum:
    name: "ruby-{{ ruby_version }}"
    state: present
    disablerepo: "rhel-7-server-rpms"

- name: Install/Update Base Ruby Gems
  command: >
    gem update --system
